import { mountDemoBar } from '../../src/lib/chrome.js';
mountDemoBar();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));

function setup(root){const list=root.querySelector('[role="tablist"]'),tabs=[...list.querySelectorAll('[role="tab"]')],manual=root.dataset.tabs==='manual';let request=0;
  function indicator(tab,instant=false){if(instant)list.classList.add('instant');list.style.setProperty('--x',`${tab.offsetLeft-list.firstElementChild.offsetLeft}px`);list.style.setProperty('--w',`${tab.offsetWidth}px`);if(instant)requestAnimationFrame(()=>list.classList.remove('instant'))}
  async function activate(tab,{focus=false,url=true}={}){const token=++request;tabs.forEach(item=>{const selected=item===tab;item.setAttribute('aria-selected',String(selected));item.tabIndex=selected?0:-1;document.getElementById(item.getAttribute('aria-controls')).hidden=!selected});indicator(tab);if(focus)tab.focus();const panel=document.getElementById(tab.getAttribute('aria-controls'));if(manual&&tab.id!=='range-day'){panel.innerHTML='<span class="pending">Loading range…</span>';await sleep(520);if(token!==request)return;const days=tab.id==='range-week'?7:30;panel.innerHTML=`<h3>${(18429*days*.82).toLocaleString()} interactions</h3><p>Loaded on explicit activation, never while focus was only exploring tabs.</p>`}if(url&&!manual){const next=new URL(location.href);next.searchParams.set('section',tab.id.replace('auto-',''));history.replaceState({},'',next)}}
  list.addEventListener('keydown',event=>{const current=tabs.indexOf(document.activeElement);if(current<0)return;const targets={ArrowRight:(current+1)%tabs.length,ArrowLeft:(current-1+tabs.length)%tabs.length,Home:0,End:tabs.length-1};if(event.key in targets){event.preventDefault();const next=tabs[targets[event.key]];next.focus();if(!manual)activate(next,{focus:false})}else if(manual&&(event.key==='Enter'||event.key===' ')){event.preventDefault();activate(tabs[current])}});list.addEventListener('click',event=>{const tab=event.target.closest('[role="tab"]');if(tab)activate(tab)});new ResizeObserver(()=>indicator(tabs.find(x=>x.getAttribute('aria-selected')==='true'),true)).observe(list);document.fonts.ready.then(()=>indicator(tabs.find(x=>x.getAttribute('aria-selected')==='true'),true));indicator(tabs[0],true);return{tabs,activate}}
const sets=[...document.querySelectorAll('[data-tabs]')].map(setup),auto=sets[0];function restore(){const key=new URL(location.href).searchParams.get('section');const tab=auto.tabs.find(x=>x.id===`auto-${key}`);if(tab)auto.activate(tab,{url:false})}addEventListener('popstate',restore);restore();
